from typing import Dict, Any
from .base_agent import BaseAgent
from ..llm import get_llm
from ..utils import safe_json_parse, logger
import json

CRITIC_SYSTEM_PROMPT = """
You are an expert Film Critic and Technical Director.
Your job is to evaluate a "Shot List" generated by a DOP for a specific screenplay scene.

Analyze the shots for:
1. **Visual Consistency**: Do they match the scene's mood?
2. **Technical Feasibility**: Are the camera movements and lighting clear?
3. **Generative Quality**: Is the "visual_prompt" detailed enough for a diffusion model (FLUX.1)?

If the shots are good, return {{"status": "approved"}}.
If they need improvement, return {{"status": "rejected", "feedback": "Specific feedback on what to fix..."}}.
"""

class CriticAgent(BaseAgent):
    def __init__(self, provider: str = "mock"):
        super().__init__(name="CriticAgent")
        self.llm = get_llm(provider)

    def run(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        script_data = input_data.get("script_data", {})
        shot_list_data = input_data.get("shot_list_data", {})
        
        logger.info(f"{self.name} evaluating shot list...")

        user_prompt = f"""
        SCENE CONTEXT:
        {json.dumps(script_data)}

        PROPOSED SHOT LIST:
        {json.dumps(shot_list_data)}

        Evaluate this shot list.
        """

        response = self.llm.generate(user_prompt, system_prompt=CRITIC_SYSTEM_PROMPT)
        return safe_json_parse(response)
